# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    vk.user:
        class:        AppBundle\Model\User\RabbitMQVKUser
    vk.from_csv:
        class:        AppBundle\Model\Input\CSVData
    vk.from_single:
        class:        AppBundle\Model\Input\SingleData
    vk.import_user_callback:
        class:        AppBundle\Consumer\UserConsumer
    vk.sdk:
        class:        BW\Vkontakte
    vk.common_api:
        class:        AppBundle\Model\VkApi\Common
        arguments: ["@vk.sdk", '%vk_access_token%']
