# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    vk.db_user:
        class:        AppBundle\Model\User\DbVkUser
        arguments: ["@vk.common_api", "@doctrine.orm.default_entity_manager", "@vk.common_api_validator"]
    vk.rabbitmq_user:
        class:        AppBundle\Model\User\RabbitMQVKUser
        arguments: ["@old_sound_rabbit_mq.import_user_producer"]
    vk.from_csv:
        class:        AppBundle\Model\Input\CSVData
    vk.from_single:
        class:        AppBundle\Model\Input\SingleData
    vk.import_user_callback:
        class:        AppBundle\Consumer\UserConsumer
        arguments: ["@vk.db_user", "@logger"]

    vk.sdk:
        class:        BW\Vkontakte
    vk.common_api:
        class:        AppBundle\Model\VkApi\Common
        arguments: ["@vk.sdk", '%vk_access_token%']
    vk.common_api_validator:
        class:        AppBundle\Model\VkApi\CommonValidator
